services:
  abtest-jaeger:
    image: jaegertracing/all-in-one:1.37
    container_name: aest-jaeger
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
#      - 5778:5778
      - 16686:16686
#      - 14268:14268
#      - 14250:14250
      - 9411:9411
#      - 16685:16685
    networks:
      abtest-network:
        ipv4_address: "192.168.10.100"
    privileged: true
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

networks:
  abtest-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          ip_range: 192.168.10.0/24