services:
  abtest-etcd:
    image: bitnami/etcd:3.5
    container_name: abtest-etcd
    restart: always
    ports:
      - 12379:2379
    networks:
      abtest-network:
        ipv4_address: "192.168.10.10"
    privileged: true
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
  abtest-mysql-userb:
    image: mysql:8.0.29
    container_name: abtest-mysql-userb
    restart: always
    ports:
      - 13306:3306
    networks:
      abtest-network:
        ipv4_address: "192.168.10.20"
    volumes:
      # init sql
      - ./configs/docker/mysql/userb:/docker-entrypoint-initdb.d
      - /Volumes/data/abtest/mysql/userb/data:/var/lib/mysql
      #- /Volumes/data/abtest/mysql/userb/conf:/etc/mysql
      - /Volumes/data/abtest/mysql/userb/mysql-files:/var/lib/mysql-files
      - /Volumes/data/abtest/mysql/userb/log:/var/log/mysql
    privileged: true
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: abtest2025
      MYSQL_USER: abtest
      MYSQL_PASSWORD: abtest2025
      ALLOW_HOST: "%"
      MYSQL_DATABASE: abtest_userb
      LANG: en_US.UTF-8
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-time-zone=+8:00'
    ]
  abtest-jaeger:
    image: jaegertracing/all-in-one:1.37
    container_name: abtest-jaeger
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
#      - 5778:5778
      - 16686:16686
#      - 14268:14268
#      - 14250:14250
      - 9411:9411
#      - 16685:16685
    networks:
      abtest-network:
        ipv4_address: "192.168.10.100"
    privileged: true
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

networks:
  abtest-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
          ip_range: 192.168.10.0/24