// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: server1.proto

package pb_server1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Server1Service_Get_FullMethodName = "/server1.Server1Service/Get"
)

// Server1ServiceClient is the client API for Server1Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Server1ServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type server1ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServer1ServiceClient(cc grpc.ClientConnInterface) Server1ServiceClient {
	return &server1ServiceClient{cc}
}

func (c *server1ServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Server1Service_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server1ServiceServer is the server API for Server1Service service.
// All implementations must embed UnimplementedServer1ServiceServer
// for forward compatibility.
type Server1ServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedServer1ServiceServer()
}

// UnimplementedServer1ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServer1ServiceServer struct{}

func (UnimplementedServer1ServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedServer1ServiceServer) mustEmbedUnimplementedServer1ServiceServer() {}
func (UnimplementedServer1ServiceServer) testEmbeddedByValue()                        {}

// UnsafeServer1ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Server1ServiceServer will
// result in compilation errors.
type UnsafeServer1ServiceServer interface {
	mustEmbedUnimplementedServer1ServiceServer()
}

func RegisterServer1ServiceServer(s grpc.ServiceRegistrar, srv Server1ServiceServer) {
	// If the following call pancis, it indicates UnimplementedServer1ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Server1Service_ServiceDesc, srv)
}

func _Server1Service_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Server1ServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server1Service_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Server1ServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Server1Service_ServiceDesc is the grpc.ServiceDesc for Server1Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server1Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server1.Server1Service",
	HandlerType: (*Server1ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Server1Service_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server1.proto",
}
