// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: server2.proto

package pb_server2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Server2Service_Get_FullMethodName = "/server2.Server2Service/Get"
)

// Server2ServiceClient is the client API for Server2Service service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Server2ServiceClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type server2ServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewServer2ServiceClient(cc grpc.ClientConnInterface) Server2ServiceClient {
	return &server2ServiceClient{cc}
}

func (c *server2ServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, Server2Service_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server2ServiceServer is the server API for Server2Service service.
// All implementations must embed UnimplementedServer2ServiceServer
// for forward compatibility.
type Server2ServiceServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
	mustEmbedUnimplementedServer2ServiceServer()
}

// UnimplementedServer2ServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServer2ServiceServer struct{}

func (UnimplementedServer2ServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedServer2ServiceServer) mustEmbedUnimplementedServer2ServiceServer() {}
func (UnimplementedServer2ServiceServer) testEmbeddedByValue()                        {}

// UnsafeServer2ServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Server2ServiceServer will
// result in compilation errors.
type UnsafeServer2ServiceServer interface {
	mustEmbedUnimplementedServer2ServiceServer()
}

func RegisterServer2ServiceServer(s grpc.ServiceRegistrar, srv Server2ServiceServer) {
	// If the following call pancis, it indicates UnimplementedServer2ServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Server2Service_ServiceDesc, srv)
}

func _Server2Service_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Server2ServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server2Service_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Server2ServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Server2Service_ServiceDesc is the grpc.ServiceDesc for Server2Service service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server2Service_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "server2.Server2Service",
	HandlerType: (*Server2ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Server2Service_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server2.proto",
}
