encoder: console
path: /var/log/ABTest/layer/
directory: layer
show_line: true
encode_level: CapitalColor
caller_type: 2
stacktrace_key: stacktrace
log_stdout: true
segment:
  max_size: 1000
  max_age: 7
  max_backups: 500
  compress: false