// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: layer.proto

package pb_layer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 层域类型枚举
type LayerType int32

const (
	LayerType_LAYER  LayerType = 0 // 层
	LayerType_DOMAIN LayerType = 1 // 域
)

// Enum value maps for LayerType.
var (
	LayerType_name = map[int32]string{
		0: "LAYER",
		1: "DOMAIN",
	}
	LayerType_value = map[string]int32{
		"LAYER":  0,
		"DOMAIN": 1,
	}
)

func (x LayerType) Enum() *LayerType {
	p := new(LayerType)
	*p = x
	return p
}

func (x LayerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LayerType) Descriptor() protoreflect.EnumDescriptor {
	return file_layer_proto_enumTypes[0].Descriptor()
}

func (LayerType) Type() protoreflect.EnumType {
	return &file_layer_proto_enumTypes[0]
}

func (x LayerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LayerType.Descriptor instead.
func (LayerType) EnumDescriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{0}
}

// 层域信息
type Layer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // 层域ID
	Type        LayerType `protobuf:"varint,2,opt,name=type,proto3,enum=layer.LayerType" json:"type,omitempty"`       // 类型（层或域）
	Name        string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`                             // 名称
	Description string    `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`               // 描述
	ParentId    string    `protobuf:"bytes,5,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`     // 父级ID
	Ratio       float32   `protobuf:"fixed32,6,opt,name=ratio,proto3" json:"ratio,omitempty"`                         // 占有父级比例
	CreatedAt   int64     `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // 创建时间 (Unix时间戳)
	UpdatedAt   int64     `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // 更新时间 (Unix时间戳)
}

func (x *Layer) Reset() {
	*x = Layer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Layer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Layer) ProtoMessage() {}

func (x *Layer) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Layer.ProtoReflect.Descriptor instead.
func (*Layer) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{0}
}

func (x *Layer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Layer) GetType() LayerType {
	if x != nil {
		return x.Type
	}
	return LayerType_LAYER
}

func (x *Layer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Layer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Layer) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Layer) GetRatio() float32 {
	if x != nil {
		return x.Ratio
	}
	return 0
}

func (x *Layer) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Layer) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// 创建层域请求
type CreateLayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer *Layer `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *CreateLayerRequest) Reset() {
	*x = CreateLayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLayerRequest) ProtoMessage() {}

func (x *CreateLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLayerRequest.ProtoReflect.Descriptor instead.
func (*CreateLayerRequest) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLayerRequest) GetLayer() *Layer {
	if x != nil {
		return x.Layer
	}
	return nil
}

// 创建层域响应
type CreateLayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer *Layer `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *CreateLayerResponse) Reset() {
	*x = CreateLayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLayerResponse) ProtoMessage() {}

func (x *CreateLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLayerResponse.ProtoReflect.Descriptor instead.
func (*CreateLayerResponse) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLayerResponse) GetLayer() *Layer {
	if x != nil {
		return x.Layer
	}
	return nil
}

// 获取层域请求
type GetLayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLayerRequest) Reset() {
	*x = GetLayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLayerRequest) ProtoMessage() {}

func (x *GetLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLayerRequest.ProtoReflect.Descriptor instead.
func (*GetLayerRequest) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{3}
}

func (x *GetLayerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 获取层域响应
type GetLayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer *Layer `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *GetLayerResponse) Reset() {
	*x = GetLayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLayerResponse) ProtoMessage() {}

func (x *GetLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLayerResponse.ProtoReflect.Descriptor instead.
func (*GetLayerResponse) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{4}
}

func (x *GetLayerResponse) GetLayer() *Layer {
	if x != nil {
		return x.Layer
	}
	return nil
}

// 更新层域请求
type UpdateLayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer *Layer `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *UpdateLayerRequest) Reset() {
	*x = UpdateLayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLayerRequest) ProtoMessage() {}

func (x *UpdateLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLayerRequest.ProtoReflect.Descriptor instead.
func (*UpdateLayerRequest) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLayerRequest) GetLayer() *Layer {
	if x != nil {
		return x.Layer
	}
	return nil
}

// 更新层域响应
type UpdateLayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer *Layer `protobuf:"bytes,1,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *UpdateLayerResponse) Reset() {
	*x = UpdateLayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLayerResponse) ProtoMessage() {}

func (x *UpdateLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLayerResponse.ProtoReflect.Descriptor instead.
func (*UpdateLayerResponse) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLayerResponse) GetLayer() *Layer {
	if x != nil {
		return x.Layer
	}
	return nil
}

// 删除层域请求
type DeleteLayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteLayerRequest) Reset() {
	*x = DeleteLayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLayerRequest) ProtoMessage() {}

func (x *DeleteLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLayerRequest.ProtoReflect.Descriptor instead.
func (*DeleteLayerRequest) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLayerRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// 删除层域响应
type DeleteLayerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteLayerResponse) Reset() {
	*x = DeleteLayerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLayerResponse) ProtoMessage() {}

func (x *DeleteLayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLayerResponse.ProtoReflect.Descriptor instead.
func (*DeleteLayerResponse) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLayerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 列出层域请求
type ListLayersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     LayerType `protobuf:"varint,1,opt,name=type,proto3,enum=layer.LayerType" json:"type,omitempty"`   // 可选，按类型筛选
	ParentId string    `protobuf:"bytes,2,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // 可选，按父级ID筛选
	Page     int32     `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32     `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListLayersRequest) Reset() {
	*x = ListLayersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLayersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLayersRequest) ProtoMessage() {}

func (x *ListLayersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLayersRequest.ProtoReflect.Descriptor instead.
func (*ListLayersRequest) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{9}
}

func (x *ListLayersRequest) GetType() LayerType {
	if x != nil {
		return x.Type
	}
	return LayerType_LAYER
}

func (x *ListLayersRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListLayersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLayersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// 列出层域响应
type ListLayersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layers []*Layer `protobuf:"bytes,1,rep,name=layers,proto3" json:"layers,omitempty"`
	Total  int32    `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListLayersResponse) Reset() {
	*x = ListLayersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_layer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLayersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLayersResponse) ProtoMessage() {}

func (x *ListLayersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_layer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLayersResponse.ProtoReflect.Descriptor instead.
func (*ListLayersResponse) Descriptor() ([]byte, []int) {
	return file_layer_proto_rawDescGZIP(), []int{10}
}

func (x *ListLayersResponse) GetLayers() []*Layer {
	if x != nil {
		return x.Layers
	}
	return nil
}

func (x *ListLayersResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_layer_proto protoreflect.FileDescriptor

var file_layer_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x22, 0xe4, 0x01, 0x0a, 0x05, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x24,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61,
	0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x38, 0x0a, 0x12, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x05,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x13, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x22, 0x21, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x38, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x22, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0c, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x05,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x39, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x05,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x22, 0x24, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07,
	0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x87, 0x01, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74,
	0x4c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x50, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e,
	0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x2a, 0x22, 0x0a, 0x09, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x09, 0x0a, 0x05, 0x4c, 0x41, 0x59, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x44,
	0x4f, 0x4d, 0x41, 0x49, 0x4e, 0x10, 0x01, 0x32, 0xe0, 0x02, 0x0a, 0x0c, 0x4c, 0x61, 0x79, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3b,
	0x0a, 0x08, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x16, 0x2e, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x61,
	0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x44, 0x0a, 0x0b, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x44, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72,
	0x12, 0x19, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x4c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x18, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x61, 0x79, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x1f, 0x5a, 0x1d, 0x2e, 0x2e,
	0x2f, 0x70, 0x62, 0x5f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x5f, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x3b, 0x70, 0x62, 0x5f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_layer_proto_rawDescOnce sync.Once
	file_layer_proto_rawDescData = file_layer_proto_rawDesc
)

func file_layer_proto_rawDescGZIP() []byte {
	file_layer_proto_rawDescOnce.Do(func() {
		file_layer_proto_rawDescData = protoimpl.X.CompressGZIP(file_layer_proto_rawDescData)
	})
	return file_layer_proto_rawDescData
}

var file_layer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_layer_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_layer_proto_goTypes = []interface{}{
	(LayerType)(0),              // 0: layer.LayerType
	(*Layer)(nil),               // 1: layer.Layer
	(*CreateLayerRequest)(nil),  // 2: layer.CreateLayerRequest
	(*CreateLayerResponse)(nil), // 3: layer.CreateLayerResponse
	(*GetLayerRequest)(nil),     // 4: layer.GetLayerRequest
	(*GetLayerResponse)(nil),    // 5: layer.GetLayerResponse
	(*UpdateLayerRequest)(nil),  // 6: layer.UpdateLayerRequest
	(*UpdateLayerResponse)(nil), // 7: layer.UpdateLayerResponse
	(*DeleteLayerRequest)(nil),  // 8: layer.DeleteLayerRequest
	(*DeleteLayerResponse)(nil), // 9: layer.DeleteLayerResponse
	(*ListLayersRequest)(nil),   // 10: layer.ListLayersRequest
	(*ListLayersResponse)(nil),  // 11: layer.ListLayersResponse
}
var file_layer_proto_depIdxs = []int32{
	0,  // 0: layer.Layer.type:type_name -> layer.LayerType
	1,  // 1: layer.CreateLayerRequest.layer:type_name -> layer.Layer
	1,  // 2: layer.CreateLayerResponse.layer:type_name -> layer.Layer
	1,  // 3: layer.GetLayerResponse.layer:type_name -> layer.Layer
	1,  // 4: layer.UpdateLayerRequest.layer:type_name -> layer.Layer
	1,  // 5: layer.UpdateLayerResponse.layer:type_name -> layer.Layer
	0,  // 6: layer.ListLayersRequest.type:type_name -> layer.LayerType
	1,  // 7: layer.ListLayersResponse.layers:type_name -> layer.Layer
	2,  // 8: layer.LayerService.CreateLayer:input_type -> layer.CreateLayerRequest
	4,  // 9: layer.LayerService.GetLayer:input_type -> layer.GetLayerRequest
	6,  // 10: layer.LayerService.UpdateLayer:input_type -> layer.UpdateLayerRequest
	8,  // 11: layer.LayerService.DeleteLayer:input_type -> layer.DeleteLayerRequest
	10, // 12: layer.LayerService.ListLayers:input_type -> layer.ListLayersRequest
	3,  // 13: layer.LayerService.CreateLayer:output_type -> layer.CreateLayerResponse
	5,  // 14: layer.LayerService.GetLayer:output_type -> layer.GetLayerResponse
	7,  // 15: layer.LayerService.UpdateLayer:output_type -> layer.UpdateLayerResponse
	9,  // 16: layer.LayerService.DeleteLayer:output_type -> layer.DeleteLayerResponse
	11, // 17: layer.LayerService.ListLayers:output_type -> layer.ListLayersResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_layer_proto_init() }
func file_layer_proto_init() {
	if File_layer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_layer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Layer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLayerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLayersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_layer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLayersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_layer_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_layer_proto_goTypes,
		DependencyIndexes: file_layer_proto_depIdxs,
		EnumInfos:         file_layer_proto_enumTypes,
		MessageInfos:      file_layer_proto_msgTypes,
	}.Build()
	File_layer_proto = out.File
	file_layer_proto_rawDesc = nil
	file_layer_proto_goTypes = nil
	file_layer_proto_depIdxs = nil
}
